<?php

/**
 * 图谱控制器
 * @author gaoqing
 * Date: 2016/3/4
 */
class PicController extends App_Controller_Action {

    private $category = null;
    private $article = null;
    private $attachment = null;
    private $zxads = null;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->category = new App_Model_Categoryurl();
        $this->article = new App_Model_Article();
        $this->attachment = new App_Model_Attachment();
        $this->zxads = new App_Model_Zxads();
    }

    /**
     * 图谱首页
     * @author gaoqing
     * @date 2016-03-04
     * @return string 视图
     */
    public function indexAction(){
        $viewName = "pic/index.tpl";
        $arr_cat_info = $this->cate_info_params;

        //获取当前栏目的信息
        $settingStr = $arr_cat_info['setting'];
        eval("\$setting=$settingStr;");
        $curChannel = array(
            'catname' => $arr_cat_info['catname'],
            'setting' => $setting,
        );

        //轮播图片
        $rotationPics = $this->getRotationPics(6, 906);

        //精彩热图
        $hotPics = $this->getHotPics();

        //广告位
        $ads_01s = $this->zxads->ads(4513);
        $ads_02s = $this->zxads->ads(4514);
        $ads_03s = $this->zxads->ads(4515);
        $pic_plus = $this->zxads->ads(4498);

        //一级子栏目文章集
        $subChannelArts = $this->getSubChannelArts(9366);

        $this->view->assign("curChannel", $curChannel);
        $this->view->assign("rotationPics", $rotationPics);
        $this->view->assign("hotPics", $hotPics);
        $this->view->assign("subChannelArts", $subChannelArts);
        $this->view->assign("ads_01s", $ads_01s);
        $this->view->assign("ads_02s", $ads_02s);
        $this->view->assign("ads_03s", $ads_03s);
        $this->view->assign("pic_plus", $pic_plus);
        $this->view->assign("pc_url", "http://pic.9939.com/");
        echo $this->view->render($viewName);
    }

    /**
     * 文章页数据集
     * @author gaoqing
     * @date 2016-03-14
     * @return string 视图
     */
    public function articledatasAction(){
        $viewName = "pic/article_datas.tpl";
        $md5URL = md5($_SERVER['REQUEST_URI']);

        //1、得到文章id $articleid
        $articleid = $this->getRequest()->getParam("articleid", 0);

        //2、根据 $articleid, 得到其相对应的栏目id: $catid 及图片附件集： $attachments
        if(isset($articleid) && !empty($articleid)){
            //得到文章所在栏目id
            $catid = $this->getCatidByArticleid($articleid);

            //根据栏目id, 得到该栏目下的文章集（不包括当前当前文章）
            $page = $this->getRequest()->getParam("page", 1);
            $url = "/pic/articledatas?articleid=" . $articleid;
            
            $articleDatas = $this->getPageInfo($page, $catid, $url, $articleid);
        }

        $this->view->assign("articleid", $articleid);
        $this->view->assign("articleDatas", $articleDatas);
        echo $this->view->render($viewName, $md5URL);
    }

    /**
     * 内容页
     * @author gaoqing
     * @date 2016-03-04
     * @return string 视图
     */
    public function articleAction(){
        $viewName = "pic/article.tpl";
        $md5URL = md5($_SERVER['REQUEST_URI']);
        /*
         * 1、得到文章id $articleid
         * 2、根据 $articleid, 得到其相对应的信息：
         *  2.1、得到当前文章的详细信息 $articleDetail
         *  2.2、栏目id: $catid 及图片附件集： $attachments
         *  2.3、上一个图集 $preArticle、$nextArticle
         */
        $pc_url = "";
        //1、得到文章id $articleid
        $articleid = $this->getRequest()->getParam("articleid", 0);

        //2、根据 $articleid, 得到其相对应的栏目id: $catid 及图片附件集： $attachments
        if(isset($articleid) && !empty($articleid)){

            //2.1、得到当前文章的详细信息 $articleDetail
            $awhere = " articleid = " . $articleid;
            $article = $this->article->getarticle($awhere);
            $pc_url = $article[0]['url'];

            //广告位
            $ads_01s = $this->zxads->ads(4523);
            $ads_02s = $this->zxads->ads(4524);
            $ads_03s = $this->zxads->ads(4525);
            $ads_04s = $this->zxads->ads(4526);
            $ads_05s = $this->zxads->ads(4531);
            $pic_plus = $this->zxads->ads(4498);

            //得到文章所在栏目id
            $catid = $this->getCatidByArticleid($articleid);

            //根据文章 id, 得到其对应的图片附件集 $attachments
            $attachments = $this->attachment->getAttsByArtid($articleid);
            $count = count($attachments);
            foreach($attachments as &$attachment){
                $attachment['url'] = $this->getPicURL($attachment['filepath']);
                $attachment['count'] = $count;
            }

            //得到相关的 6 条 最新的文章集
            $latestArticles = $this->getLatestArticles($catid, $articleid, 0, 5);

            //2.3、上一个图集 $preArticle、$nextArticle
            $preArticle = $this->article->getPreArticle($articleid, $catid);
            if(!empty($preArticle)){
                $preArticle['wap_url'] = $this->getArticleWapURL($preArticle['url']);
            }
            $nextArticle = $this->article->getNextArticle($articleid, $catid);
            if(!empty($nextArticle)){
                $nextArticle['wap_url'] = $this->getArticleWapURL($nextArticle['url']);
            }
        }
        //热图推荐部分
        $hotPics = $this->getRotationPics(6, 4527);
        $hotPics = $this->perDoubleGroup($hotPics);

        $this->view->assign("articleid", $articleid);
        $this->view->assign("articleurl", "/pic/article/" . $articleid . ".shtml");
        $this->view->assign("attachments", $attachments);
        $this->view->assign("article", $article);
        $this->view->assign("preArticle", $preArticle);
        $this->view->assign("nextArticle", $nextArticle);
        $this->view->assign("latestArticles", $latestArticles);
        $this->view->assign("ads_01s", $ads_01s);
        $this->view->assign("ads_02s", $ads_02s);
        $this->view->assign("ads_03s", $ads_03s);
        $this->view->assign("ads_04s", $ads_04s);
        $this->view->assign("ads_05s", $ads_05s);
        $this->view->assign("pic_plus", $pic_plus);
        $this->view->assign("hotPics", $hotPics);
        $this->view->assign("pc_url", $pc_url);
        echo $this->view->render($viewName, $md5URL);
    }

    /**
     * 多列表页
     * @author gaoqing
     * @date 2016-03-04
     * @return string 视图
     */
    public function mlistAction(){
        $viewName = "pic/mlist.tpl";
        $md5URL = md5($_SERVER['REQUEST_URI']);

        $arr_cat_info = $this->cate_info_params;
        $catid = $arr_cat_info['catid'];

        //查询当前栏目的父级信息
        $parents = $this->getParentInfo($arr_cat_info['arrparentid']);

        //广告位
        $ads_01s = $this->zxads->ads(4516);
        $ads_02s = $this->zxads->ads(4517);
        $ads_03s = $this->zxads->ads(4518);
        $pic_plus = $this->zxads->ads(4498);

        //得到轮播图信息
        $arrparentid = $arr_cat_info['arrparentid'];
        $rotationPics = $this->getChannelRotationPics($catid, 4, $arrparentid);

        //得到当前栏目下：$catid 的所有子栏目 $subChannels
        $subChannelArts = $this->getSubChannelArts($catid);

        //获取当前栏目的信息
        $settingStr = $arr_cat_info['setting'];
        eval("\$setting=$settingStr;");
        $curChannel = array(
            'catid' => $catid,
            'catname' => $arr_cat_info['catname'],
            'url' => $this->getChannelWapURL($arr_cat_info['child'], $arr_cat_info['url']),
            'channel_url' => $arr_cat_info['channel_url'],
            'parent' => $parents,
            'setting' => $setting,
            );
        //热图推荐部分
        $hotPics = $this->getRotationPics(6, 4527);
        $hotPics = $this->perDoubleGroup($hotPics);

        $this->view->assign("curChannel", $curChannel);
        $this->view->assign("rotationPics", $rotationPics);
        $this->view->assign("subChannelArts", $subChannelArts);
        $this->view->assign("ads_01s", $ads_01s);
        $this->view->assign("ads_02s", $ads_02s);
        $this->view->assign("ads_03s", $ads_03s);
        $this->view->assign("pic_plus", $pic_plus);
        $this->view->assign("hotPics", $hotPics);
        $this->view->assign("pc_url", $arr_cat_info['pc_url']);
        echo $this->view->render($viewName, $md5URL);
    }

    /**
     * 单列表页
     * @author gaoqing
     * @date 2016-03-04
     * @return string 视图
     */
    public function slistAction(){
        $viewName = "pic/slist.tpl";
        $md5URL = md5($_SERVER['REQUEST_URI']);

        $flag = $this->getRequest()->getParam("flag", "");
        $urlPart = trim($flag, "/");
        $arr_cat_info = $this->cate_info_params;

        //查询当前栏目的父级信息
        $parents = $this->getParentInfo($arr_cat_info['arrparentid']);

        //得到轮播图信息
        $arrparentid = $arr_cat_info['arrparentid'];
        $rotationPics = $this->getChannelRotationPics($arr_cat_info['parentid'], 4, $arrparentid);

        //广告位
        $ads_01s = $this->zxads->ads(4519);
        $ads_02s = $this->zxads->ads(4520);
        $ads_03s = $this->zxads->ads(4521);
        $ads_04s = $this->zxads->ads(4522);
        $pic_plus = $this->zxads->ads(4498);

        //当前频道下的图集（分页）
        $page = $this->getRequest()->getParam("page", 1);
        $uri = "/pic/" . $urlPart . "/list.shtml";
        $articleDatas = $this->getPageInfo($page, $arr_cat_info['catid'], $uri);

        //获取当前栏目的信息
        $settingStr = $arr_cat_info['setting'];
        eval("\$setting=$settingStr;");
        $curChannel = array(
            'catid' => $arr_cat_info['catid'],
            'catname' => $arr_cat_info['catname'],
            'url' => $this->getChannelWapURL($arr_cat_info['child'], $arr_cat_info['url']),
            'channel_url' => $arr_cat_info['channel_url'],
            'parent' => $parents,
            'setting' => $setting,
        );
        //热图推荐部分
        $hotPics = $this->getRotationPics(6, 4527);
        $hotPics = $this->perDoubleGroup($hotPics);

        $this->view->assign("curChannel", $curChannel);
        $this->view->assign("rotationPics", $rotationPics);
        $this->view->assign("articleDatas", $articleDatas);
        $this->view->assign("ads_01s", $ads_01s);
        $this->view->assign("ads_02s", $ads_02s);
        $this->view->assign("ads_03s", $ads_03s);
        $this->view->assign("ads_04s", $ads_04s);
        $this->view->assign("pic_plus", $pic_plus);
        $this->view->assign("hotPics", $hotPics);
        $this->view->assign("page", $page);
        $this->view->assign("pc_url", $arr_cat_info['pc_url']);
        echo $this->view->render($viewName, $md5URL);
    }

    /**
     * 根据父级 id 字符串集，查询其所有父级栏目的信息
     * @author gaoqing
     * @date 2016-03-04
     * @param string $arrparentid 父级 id 字符串集
     * @return array 所有父级栏目的信息
     */
    private function getParentInfo($arrparentid){
        $parents = array();
        if (isset($arrparentid) && !empty($arrparentid)){
            $arrparentid = ltrim($arrparentid, "0,");
            $parents = $this->category->getAllCategory($arrparentid);
            foreach($parents as &$parent){
                $url = $this->getChannelWapURL($parent['child'], $parent['url']);
                $parent['url'] = $url;
            }
        }
        return $parents;
    }

    /**
     * 得到栏目下的轮播图信息
     * @author gaoqing
     * @date 2016-03-04
     * @param int $catid 栏目id
     * @param string $arrparentid 父级 id 字符串集
     * @return array 轮播图信息集
     */
    private function getChannelRotationPics($catid, $size, $arrparentid = ''){
        $rotationPics = array();

        if(isset($catid) && !empty($catid)){
            $map_focus = array(
                '9367' => 4187, //身体部位
                '9368' => 4188, //孕育探秘
                '9369' => 4189, //中药图林
                '9370' => 4190, //医学纵览
                '9371' => 4191, //病态视角
                '9372' => 4192, //男人视觉
                '9373' => 4193, //时尚女性
                '9374' => 4194, //保健图库
                '9375' => 4195, //美容图潮
                '9376' => 4196, //两性图谱
                '9479' => 4197, //图说视界
                '9366' => 4196 //图说视界
            );
            if(!isset($map_focus[$catid])){
                //得到有轮播图的最近父级的 id 值
                if(!empty($arrparentid)){
                    $arrparentid = ltrim($arrparentid, "0,");
                    $arrparentidArr = explode(",", $arrparentid);
                    $arrparentidArr = array_reverse($arrparentidArr);
                    foreach($arrparentidArr as $parentid){
                        if(isset($map_focus[$parentid])){
                            $catid = $parentid;
                        }
                    }
                }
            }
            $adid = $map_focus[$catid];
            $zx_ads = $this->getRotationPics($size, $adid);
        }
        $rotationPics = $zx_ads;
        return $rotationPics;
    }

    /**
     * 得到指定频道下的文章集
     * @author gaoqing
     * @date 2016-03-07
     * @param int $channelid 频道id
     * @param int $count 查询的条数
     * @param int $articleid 剔除的文章 id (如果不为0，则不包含 $articleid 的值)
     * @return array 指定频道下的文章集
     */
    private function getChannelArts($channelid, $offset, $count, $articleid = 0){
        $articles = array();
        /*
         * 1、得到指定频道的下，指定条数的文章集 $articles
         * 2、根据文章集 $articles ，循环查询，得到对应的 $pics
         */
        $reject = " ";
        if(!empty($articleid)){
            $reject .= " AND articleid != '" . $articleid . "'";
        }
        $where = " catid = '". $channelid ."' ". $reject ." AND status = 20 order by articleid DESC LIMIT ". $offset .", ". $count ." ";
        $articles = $this->article->getarticle($where);
        if(isset($articles) && !empty($articles)){
            foreach($articles as &$article){
                $article = $this->handleArticle($article);
            }
        }
        return $articles;
    }

    /**
     * 得到当前频道下，【更多】操作的 url 地址
     * @author gaoqing
     * @date 2016-03-07
     * @param int $catid 栏目 id
     * @return string 【更多】操作的 url 地址
     */
    private function getChannelWapURLByCatid($catid){
        $categoryM = new App_Model_Categoryurl();

        //查询当前频道的信息
        $where = " catid = ". $catid ." ";
        $category = $categoryM->getcategory($where);

        //得到当前频道的 url 值
        $murl = $this->getChannelWapURL($category[0]['child'], $category[0]['url']);
        return $murl;
    }

    /**
     * 得到分页代码
     * @author gaoqing
     * @date 2016-03-07
     * @param int $page 当前页
     * @param int $pages 总页数
     * @param int $uri uri 值
     * @return string 分页代码
     */
    private function getPageHTML($page, $pages, $uri){
        $pageHTML = '';
        $spliter = "?";
        if(strstr($uri, "?")){
            $spliter = "&";
        }
        $prePageHTML = '<a href="'. $uri . $spliter . 'page='. ($page - 1) .'">上一页</a>';
        if($page == 1){
            $prePageHTML = '';
        }
        $currPageHTML = '<span>'. $page .'/'. $pages .'</span>';

        $nextPageHTML = '<a href="'. $uri . $spliter . 'page='. ($page + 1) .'">下一页</a>';
        if($page == $pages){
            $nextPageHTML = '';
        }
        $pageHTML = $prePageHTML . $currPageHTML . $nextPageHTML;
        return $pageHTML;
    }

    /**
     * 得到 ajax 方式的分页代码
     * @author gaoqing
     * @date 2016-03-07
     * @param int $page 当前页
     * @param int $pages 总页数
     * @param int $articleid 文章的 id
     * @return string 分页代码
     */
    private function getAjaxPageHTML($page, $pages, $articleid){
        $pageHTML = '';
        $prePageHTML = '<a href="javascript:paging('. $articleid .', '. ($page - 1) .')">上一页</a>';
        if($page == 1){
            $prePageHTML = '';
        }
        $currPageHTML = '<span>'. $page .'/'. $pages .'</span>';

        $nextPageHTML = '<a href="javascript:paging('. $articleid .', '. ($page + 1) .')">下一页</a>';
        if($page == $pages){
            $nextPageHTML = '';
        }
        $pageHTML = $prePageHTML . $currPageHTML . $nextPageHTML;
        return $pageHTML;
    }

    /**
     * 得到分页信息集
     * @author gaoqing
     * @date 2015-03-07
     * @param int $page 当前页
     * @param int $catid 栏目id
     * @param int $uri uri 值
     * @param int $articleid 剔除的文章 id (如果不为0，则不包含 $articleid 的值)
     * @return array 分页信息集
     */
    private function getPageInfo($page, $catid, $uri, $articleid = 0)
    {
        $size = 12;
        $offset = ($page - 1) * $size;
        $reject = " ";
        if(!empty($articleid)){
            $reject .= " AND articleid != '" . $articleid . "'";
        }
        $where = " catid = '" . $catid . "' ". $reject ." AND status = 20 ";
        $total = $this->article->getcount($where);
        $pages = ceil($total / $size);

        $articles = $this->getChannelArts($catid, $offset, $size, $articleid);
        foreach($articles as &$article){
            $article['url'] = $this->getArticleWapURL($article['url']);
        }
        $pageHTML = $this->getPageHTML($page, $pages, $uri);
        if(!empty($articleid)){
            $pageHTML = $this->getAjaxPageHTML($page, $pages, $articleid);
        }
        $articleDatas = array(
            "articles" => $articles,
            "pageHTML" => $pageHTML,
        );
        return $articleDatas;
    }

    /**
     * 得到当前频道下的所有子栏目的文章
     * @author gaoqing
     * @date 2016-03-08
     * @param int $catid 栏目id
     * @return array 所有子栏目的文章集
     */
    private function getSubChannelArts($catid){
        $subChannelArts = array();
        $where = " parentid = " . $catid;
        $subChannels = $this->category->getcategory($where);
        if (isset($subChannels) && !empty($subChannels)) {
            $innerArr = array();
            foreach ($subChannels as $subChannel) {
                $channelArts = $this->getChannelArts($subChannel['catid'], 0, 4);
                foreach($channelArts as &$channelArt){
                    $channelArt['url'] = $this->getArticleWapURL($channelArt['url']);
                }
                $channelMoreURL = $this->getChannelWapURL($subChannel['child'], $subChannel['url']);

                $innerArr['catname'] = $subChannel['catname'];
                $innerArr['articles'] = $channelArts;
                $innerArr['moreurl'] = $channelMoreURL;

                $subChannelArts[] = $innerArr;
            }
            return $subChannelArts;
        }
        return $subChannelArts;
    }

    /**
     * 得到 wap 端的 url 地址
     * @author gaoqing
     * @date 2016-03-08
     * @param int $child 是否有子栏目（0：没有；1：有）
     * @param string $picURL pc端 url 地址
     * @return string wap 端的 url 地址
     */
    private function getChannelWapURL($child, $picURL)
    {
        $wapURL = "/";
        $matchArr = $this->resolveURL($picURL);
        if(!empty($matchArr)){
            $wapURL .= $matchArr[1] . DIRECTORY_SEPARATOR;
        }
        if(isset($matchArr[2]) && !empty($matchArr[2])){
            $wapURL .= $matchArr[2] . DIRECTORY_SEPARATOR;
        }
        if($child == 0){
            $wapURL .= "list.shtml";
        }
        return $wapURL;
    }

    /**
     * 得到文章的 wap 端 url 地址
     * @author gaoqing
     * @date 2016-03-08
     * @param string $pcURL PC 端 URL 地址
     * @return string wap端 url 地址
     */
    private function getArticleWapURL($pcURL) {
        $wapURL = $pcURL;
        if (isset($pcURL) && !empty($pcURL)) {

            //具体的文章内容路径处理方式：
            if (strpos($pcURL, ".shtml")) {

                $linkURArr = explode("/", $pcURL);
                //获取域名：
                $fullDomain = $linkURArr[2];
                $domainArr = explode(".", $fullDomain);
                $domain = $domainArr[0];

                //获取文章id
                $linkURArrLength = count($linkURArr);
                $articleidStr = $linkURArr[$linkURArrLength - 1];
                $articleidArr = explode(".", $articleidStr);
                $articleid = empty($articleidArr) ? 0 : $articleidArr[0];

                $wapURL = "/" . $domain . "/article/" . $articleid . ".shtml";
                return $wapURL;
            }
        }
        return $wapURL;
    }

    /**
     * 得到轮播图集
     * @author gaoqing
     * @date 2016-03-08
     * @param int $size 获取的数量
     * @param int $adid 广告位id
     * @return array 轮播图集
     */
    private function getRotationPics($size, $adid)
    {
        $zx_ads = array();
        $_zxads_obj = new App_Model_Zxads();
        //获取资讯广告 广告位轮闪（图片或者文字链）
        $zx_where = " placeid='" . $adid . "' ";    //3685
        $zx_adsplace = $_zxads_obj->Getadsplace($zx_where);
        if(isset($zx_adsplace) && !empty($zx_adsplace)){
            $where = " placeid='" . $zx_adsplace[0]['placeid'] . "' order by addtime desc limit 0," . $size . "";
            $zx_ads = $_zxads_obj->Getads($where);
            if ($zx_ads && is_array($zx_ads)) {
                foreach ($zx_ads as $key_ads => $val_ads) {
                    if ($val_ads['imageurl']) {
                        $zx_ads[$key_ads]['imageurl'] = "http://www.9939.com/uploadfile/" . $val_ads['imageurl'];
                        $zx_ads[$key_ads]['linkurl'] = $this->getArticleWapURL($val_ads['linkurl']);
                    }
                }
                return $zx_ads;
            }
        }
        return $zx_ads;
    }

    /**
     * 得到精彩热图数据集
     * @author gaoqing
     * @date 2016-03-08
     * @return array 精彩热图集
     */
    private function getHotPics(){
        $hotPics = array();
        $count = 4;
        
        $awhere='';
        $index_name = '';
        $tmp_father_id = '9366';
        if(isset(QConfigs_Site_Config::$site_template_map[$tmp_father_id])){
            $awhere = " channel_id ='$tmp_father_id'  AND status = 20 ORDER BY articleid DESC LIMIT 0, " . $count;
        }else{
            $cwhere = " catid = '$tmp_father_id'";
            $arrchildid = "";
            $categories = $this->category->getcategory($cwhere);
            $arrchildid = isset($categories) ? ($categories[0]['arrchildid']) : "";
            $awhere = " catid in(". $arrchildid .") AND status = 20 ORDER BY articleid DESC LIMIT 0, " . $count;
            $index_name = 'index_cat_status_articleid';
        }
        $hotPics = $this->article->getarticle($awhere, $index_name);
        
        foreach($hotPics as &$hotPic){
            $hotPic['url'] = $this->getArticleWapURL($hotPic['url']);
            $hotPic = $this->handleArticle($hotPic);
            //得到其三张附件
            $attachment = $this->attachment->getAttsByArtid($hotPic['articleid'], 3, 0);
            foreach($attachment as &$val){
                $val['url'] = $this->getPicURL($val['filepath']);
            }
            $hotPic['attachment'] = $attachment;
        }
        return $hotPics;
    }

    /**
     * 处理文章的相关信息
     * @author gaoqing
     * @date 2016-03-08
     * @param array $article 文章信息
     * @return array 处理后的文章信息
     */
    private function handleArticle($article)
    {
        $article['date'] = date('Y-m-d', $article['inputtime']);

        //判断当前文章是否有缩略图，如果没有，则取出对应图集的第一张图
        if (!isset($article['thumb']) || empty($article['thumb'])) {
            $temp = $this->attachment->getAttsByArtid($article['articleid'], 1, 0);
            if (isset($temp) && !empty($temp)) {
                $article['thumb'] = $temp[0]['filepath'];
            }
        }
        //判断 thumb 路径中，是否包含 【uploadfile】路径，如果没有，则添加该路径
        $article['thumb'] = $this->getPicURL($article['thumb']);

        //得到当前文章的附件总数
        $article['thumb_count'] = $this->attachment->getAttSizeByArtid($article['articleid']);
        return $article;
    }

    /**
     * 得到图片的路径
     * @author gaoqing
     * @date 2016-03-09
     * @param string $partURL 图片部分路径
     * @return string 完整图片的路径
     */
    private function getPicURL($partURL){
        $picURL = "";
        $init_temp = strstr($partURL, 'uploadfile');
        $file_folder = empty($init_temp) ? '/uploadfile/' : '/';
        $picURL = 'http://www.9939.com' . $file_folder . $partURL;
        return $picURL;
    }

    /**
     * 根据文章id, 得到其所在栏目的id
     * @author gaoqing
     * @date 2016-03-09
     * @param int $articleid 文章id
     * @return int 栏目的id
     */
    private function getCatidByArticleid($articleid)
    {
        $catid = 9366;
        $awhere = " articleid = '" . $articleid . "' AND status = 20 ";
        $articleInfo = $this->article->getarticle($awhere);
        if (isset($articleInfo) && !empty($articleInfo)) {
            $catid = $articleInfo[0]['catid'];
            return $catid;
        }
        return $catid;
    }

    /**
     * 得到最近的与当前文章相关的最新文章
     * @author gaoqing
     * @date 2016-03-10
     * @param int $catid 栏目id
     * @param int $articleid 文章id
     * @param int $offset 查询起始位置
     * @param int $count 查询数
     * @return array 与当前文章相关的最新文章集
     */
    private function getLatestArticles($catid, $articleid, $offset, $count){
        $latestArticles = array();
        $latestArticles = $this->article->getLatestArticles($catid, $articleid, $offset, $count);

        //删除当前 $articleid 的值
        $removeKey = count($latestArticles) - 1;
        foreach($latestArticles as $key => &$article){
            if($article['articleid'] == $articleid){
                $removeKey = $key;
                continue;
            }
            $article = $this->handleArticle($article);
            $article['url'] = $this->getArticleWapURL($article['url']);
        }
        array_splice($latestArticles, $removeKey, 1);
        return $latestArticles;
    }

    /**
     * 将数组，拆分为，没两个值一组，再封装到一个数组中
     * @author gaoqing
     * @date 2016-03-11
     * @param array $initArr 初始化数组
     * @return array 封装后的数组
     */
    private function perDoubleGroup($initArr){
        $perDoubleGroup = array();

        if(isset($initArr) && !empty($initArr)){
            $inner = array();
            foreach($initArr as $key => $val){
                $inner[] = $val;
                if($key % 2 == 1){
                    $perDoubleGroup[] = $inner;
                    $inner = array();
                }
            }
        }
        return $perDoubleGroup;
    }


}